# Generated by Django 3.2.9 on 2022-01-25 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0011_auto_20220125_1607'),
        ('Teacher', '0015_learningcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToStudent',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.student')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.teacher')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
    ]
