# Generated by Django 3.2.9 on 2022-01-25 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_alter_manager_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Message', '0002_managertousers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerToUsers',
            new_name='ManagerToUser',
        ),
    ]
