# Generated by Django 3.2.9 on 2022-01-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20220120_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
