# Generated by Django 3.2.9 on 2022-01-23 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_auto_20220121_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkTeacherCanAdd',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='HomeworkImages/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='home_work',
            field=models.ManyToManyField(blank=True, null=True, to='Teacher.HomeworkTeacherCanAdd'),
        ),
    ]
