# Generated by Django 3.2.9 on 2022-01-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_auto_20220123_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='home_work',
            field=models.ManyToManyField(to='Teacher.HomeworkTeacherCanAdd'),
        ),
    ]
