# Generated by Django 3.2.9 on 2022-01-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_alter_classroom_home_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='home_work',
        ),
    ]
