# Generated by Django 3.2.9 on 2022-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_remove_classroom_home_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='homework',
            field=models.ManyToManyField(to='Teacher.HomeworkTeacherCanAdd'),
        ),
    ]
