# Generated by Django 3.2.9 on 2022-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_post',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('teacher', 'Teacher'), ('student', 'Student')], default=None, max_length=75),
        ),
    ]
