# Generated by Django 3.2.9 on 2022-01-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_user_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('can_view_manager', 'Can view manager')]},
        ),
    ]
