# Generated by Django 3.2.9 on 2022-01-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
