# Generated by Django 3.2.9 on 2022-01-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='date_joined',
            new_name='created',
        ),
    ]
