# Generated by Django 3.2.9 on 2022-01-19 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_date_joined_studentprofile_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('class_hours', models.CharField(help_text='Set class hours -> 6:45PM - 8:00PM', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
