# Generated by Django 3.2.9 on 2022-01-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('Student', '0003_studentclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classroom'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(upload_to='StudentImages/'),
        ),
    ]
