# Generated by Django 3.2.9 on 2022-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20220120_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='StudentImage/default.jpg', upload_to='StudentImages/'),
        ),
    ]
