# Generated by Django 3.2.9 on 2022-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_rename_studentprofile_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkStudentCanAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
