# Generated by Django 3.2.9 on 2022-01-25 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0014_auto_20220125_1607'),
        ('Student', '0010_homeworkstudentcanadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkStudentAdd',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='HomeworkImages/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classroom')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeworkStudentCanAdd',
        ),
    ]
