# Generated by Django 3.2.9 on 2022-01-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': (('can_view_manager', 'Can view manager'), ('can_add_student', 'Can add student'), ('can_add_student_profile', 'Can add student profile'), ('can_change_student', 'Can change student'), ('can_change_student_profile', 'Can change student profile'), ('can_delete_student', 'Can delete student'), ('can_delete_student_profile', 'Can delete student profile'), ('can_view_student', 'Can view student'), ('can_view_student_profile', 'Can view student profile'))},
        ),
    ]
