# Generated by Django 3.2.9 on 2022-01-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
    ]
