# Generated by Django 3.2.9 on 2022-01-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_auto_20220123_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerPermissions',
        ),
    ]
