# Generated by Django 3.2.9 on 2022-01-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_delete_managerpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': [('can_view_manager', 'Can view manager'), ('can_add_student', 'Can add student')]},
        ),
    ]
