# Generated by Django 3.2.9 on 2022-01-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
    ]
